name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted  # Using self-hosted runner instead of GitHub's runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host 192.168.1.244" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          chmod 600 $HOME/.ssh/id_ed25519 || true
      
      - name: Deploy to server
        run: |
          # Ensure target directory exists
          ssh -i $HOME/.ssh/id_ed25519 -p 9923 deployadmin@192.168.1.244 "mkdir -p ~/nodejs-mongo-api"
          
          # Stop existing application if running
          ssh -i $HOME/.ssh/id_ed25519 -p 9923 deployadmin@192.168.1.244 "pm2 delete nodejs-mongo-api || true"
          
          # Copy files to server
          rsync -avz --delete -e "ssh -i $HOME/.ssh/id_ed25519 -p 9923" ./ deployadmin@192.168.1.244:~/nodejs-mongo-api/
          
          # Ensure correct Node.js version and update NPM
          ssh -i $HOME/.ssh/id_ed25519 -p 9923 deployadmin@192.168.1.244 "source ~/.nvm/nvm.sh && nvm install 18 && nvm use 18 || (curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && source ~/.nvm/nvm.sh && nvm install 18 && nvm use 18)"
          
          # Install dependencies and start application
          ssh -i $HOME/.ssh/id_ed25519 -p 9923 deployadmin@192.168.1.244 "cd ~/nodejs-mongo-api && source ~/.nvm/nvm.sh && npm install --production && pm2 start npm --name nodejs-mongo-api -- start"
